---
server:
  address: localhost
  port: 8082
akka:
  number.of.shards: 10
cassandra:
  keySpace: system # Change this to a application keyspace. Cassandra driver needs a keyspace and using system keyspace for now to make it easy to get going but is a BAD practice
  contactPoints: localhost
  port: 9042
management:
  port: 8083

